version: "3.9"

services:
  whikers:
    container_name: whikers
    image: whikers-anime
    build: .
    env_file:
      - .env
    ports:
      - "8000:3001"
    depends_on:
      whiskers_db:
        condition: service_healthy
      redis:
        condition: service_started
      
  whiskers_db:
    container_name: whiskers_db
    image: postgres:14
    environment:                                                                                                                                       
      POSTGRES_PASSWORD: "${DB_PASSWORD}"                                                                                                            
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: whiskers_redis
    image: redis:latest
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
     - "6380:6379"
    deploy:
      resources: 
        limits:
          cpus: '0.2'
          memory: '0.4GB'

      

volumes:
  pgdata: {}